#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

# template for each entry, it contains the syscall name as a global label
# and the code to invoke the syscall
# li a7, SYS_<name> will load the syscall number into a7, while a0-a7 are caller-saved
# NOTE: a0-a7 是调用者保存，其中 a0 是返回值寄存器（同时也作为第一个参数寄存器）
# a7 虽然是参数寄存器，但在系统调用中有特殊用途，详细见 kernel/syscall.c
sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    # environment call 指令，触发陷入内核态 
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
